name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v2

      # Generate the snake animation
      - uses: Platane/snk@v2  # Use a specific version instead of "master"
        id: snake-gif
        with:
          github_user_name: EinMelih
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build for debugging
      - run: git status

      # Push the generated snake files to the `output` branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Use a specific version instead of "master"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Deploy the generated files to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
